# https://dn42.net/howto/networksettings
- name: Configure sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - {name: 'net.ipv4.conf.default.rp_filter', value: '2'}
    - {name: 'net.ipv4.conf.all.rp_filter', value: '2'}
    - {name: 'net.ipv4.conf.all.forwarding', value: '1'}
    - {name: 'net.ipv6.conf.all.forwarding', value: '1'}

- name: Install dn42 ROA sync script
  block:
  - name: Upload dn42 ROA sync script
    copy:
      src: dn42-update-roas.sh
      dest: "{{ automation_root_dir }}/dn42-update-roas.sh"
      owner: root
      group: adm
      mode: '0755'
  - name: Run dn42 ROA sync script
    command: "{{ automation_root_dir }}/dn42-update-roas.sh"
    become: yes
    become_user: bird
    ignore_errors: "{{ ansible_check_mode }}"
  - name: Create cron job for dn42 ROA sync script
    cron:
      name: "Pull dn42 ROA tables"
      minute: "5"
      job: "{{ automation_root_dir }}/dn42-update-roas.sh"
      user: bird
  when: "'dn42routers' in group_names or import_roa|default(False)"