routers:
  hosts:
    yuuko:
      ansible_host: yuuko.kitauji.net
      ownip: 172.22.179.98
      ownip6: 
      # dn42_regions:
      location: 
      wg_pubkey:
      link_local_v6:
      link_local_v4:
      peerfinder_uuid:
      v4_only:
      sysLocation: "Parent's house"
    natsuki:
      ansible_host: natsuki.kitauji.net
      sysLocation: "Office desk"
    kanade:
      ansible_host: wireguard03.kitauji.net
      sysLocation: "Kanade machine @ apt"
    asuka:
      ansible_host: asuka.kitauji.net
      sysLocation: "Garrett's parent's house"
    haruka:
      ansible_host: haruka.kitauji.net
      sysLocation: "Grandma's house"
    midori:
      ansible_host: midori.kitauji.net
      sysLocation: "Office desk"
    ririka:
      ansible_host: ririka.kitauji.net
      sysLocation: "Apt"
    kix-kitauji:
      ansible_host: kix-kitauji.kitauji.net
      sysLocation: "Shuuichi machine @ apt"
    hazuki:
      ansible_host: hazuki.kitauji.net
      sysLocation: "Oracle VM @ VA"
        